language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
